language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: "IrDDhs/1oB+ZlyN97JfZs5IMvcwGLnDTtweWmw3VZqaoSZV5n3UQ2hngU59QJfD1SwNbATEzNvcNIfSJMV4EFpPUz8XpQ2mBzhsjnqlB7o9WfFNHj/ou6G39QEn6ccFXTIfzC6zjHUyP5FqmBn8GuEb/Vf0RHP1VRoY/Tf2a48ubz7N9qR7xbeYCIRQg3Osf860OW6eOn3oTAJYza6fKZy6Ja4oDXts67bWQFN+i7yZom50qgMRqDoQEZCwKWa50vC2qyYnGJv7nJDUEf3A93nx7LEPBEtkRw7SneTcAhowv6dygfW5obdlggC9JeVnYAuEsz8mmMbBpnZdX+WHGprxZ0y48ekT4T61WhjTsPJgXT6Mh42mDlVj3M/f4WSQMu9EAhDIevdjz4/BMGPEE/lCYpPffcgeEft/prYnaARR8aAKaTYBDTokTBEsh/0cQCW/iMc7RB56UQvK0UYF7kpDHisMdOHvBEfBlv2uvtBJ7VHNgtVA6MN8yTf1CFF7roxbuZMY5zeFiow8q3smmS7k0bGx7QPKpJVl69Ie2wV8PWVvkIG+eBTjvqSdRYXnmChvtqs1gwkcKkAzCSy7cYSy2bi0wooV12oQSm/5rB+afJlSzmCI8GVOEwGMMOd41Y+yojOWKvrbQ/pmS+xbMhFBSxSTpQOQMaC+G67aM4Gs="